use country;
select * from country;
select name,continent, concat (continent,'have',name,'country') from country;
select name,continent, concat_ws (' ',continent,'have',name,'country') from country;
select name, concat (name,'country') from country;
select name, concat_ws(' ',name,'country') from country;
select name,upper(name),substr(name,2) from country;
select name ,substr(name,-4) from country;
select name ,substr(name,2) ,substr(name ,2,4),substr(name,1,4) from country where name ='colombia';
select name ,substr(name,-4,2) from country;
select name , length(name),char_length(name) from country;
select length('4'),char_length('@');
select name , replace(name,'a','e') from country;
select name , replace(name,'a','@') from country;
select trim('     hello world     ');
select name , lpad(name,6,'-')from country;
select name , lpad(name,9,'-')from country;
select name , rpad(name,6,'-')from country;
select name , rpad(name,9,'-')from country;
select current_date();
select current_time();
select now();
select current_timestamp();
select now(),adddate(now(),-2); 
select now(),adddate(now(),+2); 
select adddate(now(),interval 1 year),adddate(now(),interval 1 month),adddate(now(),interval 1 quarter);
select now(), year(now());
select now(), month(now());
select extract(month from now());
select extract(minute from now());
SELECT EXTRACT(YEAR FROM NOW());
SELECT EXTRACT(MONTH FROM NOW());
SELECT EXTRACT(DAY FROM NOW());
SELECT EXTRACT(HOUR FROM NOW());
SELECT EXTRACT(MINUTE FROM NOW());
SELECT EXTRACT(SECOND FROM NOW());
select dayname(now());
select weekday(now());
select now(),date_format(now(),'year is %y month is %m ,weekday is %m');


